- name: Docker Installing and Managing

  hosts: pod-aldialvayadi2-managed2
  become: true

  tasks:
    - name: Updating Package
      command: apt-get update -y

    - name: Installing Software
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      apt: name={{ item }} state=latest update_cache=yes
    
    - name: Fingerprint
      command: apt-key fingerprint 0EBFCD88

    - name: Adding Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Updating Package
      apt: state=latest update_cache=yes
     
    - name: Installing Docker Package
      apt: name={{ item.package }} state=latest
      loop:
        - package: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Create Nginx Container Pod Default

  hosts: pod-aldialvayadi2-managed2
  become: true
  
  tasks:
    - name: Downloading Web Content
      ansible.builtin.git:
        repo: https://github.com/gabrielecirulli/2048.git
        dest: /home/aldialvayadi2/2048
        separate_git_dir: /home/aldialvayadi2/2048.git
   
    - name: Running and Creating Container Default
      docker_container:
        name: nginx-pod-aldialvayadi2-default
        image: nginx
        published_ports: 8080:80
        state: started

    - name: Running and Creating Container2048
      docker_container:
        name: nginx-pod-aldialvayadi2-2048
        image: nginx
        published_ports: 2048:80
        volumes: /home/aldialvayadi2/2048/:/usr/share/nginx/html
        state: started

